### ISSUE TITLE
ANSI keyboard breaks

### ISSUE THREAD

**Issue by HackerFantastic** [ayufan-rock64/pinebook-pro-keyboard-updater#11]
When running the firmware updater on ANSI keyboard PBP, it will break the keyboard rendering it useless. The track pad still appears to work but all keyboard input is erroneous once step-1 is applied. The firmware does not work with ANSI keyboard and should not be applied to ANSI PBP models.

**Comment by ayufan** [comment]
Thanks for heads-up.

**Comment by HackerFantastic** [comment]
sure, I have tried to "read" out the firmware from my keyboard but get all 0x0 - should just be a case of someone sharing a proper .hex firmware file to flash on the ANSI models.

**Comment by ayufan** [comment]
@HackerFantastic Can you try latest updated instructions? It should bring ANSI back to alive :)

**Comment by HackerFantastic** [comment]
Hi @ayufan, the latest firmware worked perfectly. Just tested it this morning! thank you for the fast fix!
