### ISSUE TITLE
Command to check if keyboard and trackpad have already been updated

### ISSUE THREAD

**Issue by yawnoc** [ayufan-rock64/pinebook-pro-keyboard-updater#16]
I received a Pinebook Pro on 17 Jan 2020, and **I believe the keyboard/trackpad have already been updated**; I am able to type the correct characters while touching the trackpad, and the trackpad seems OK (although it can't move the pointer while I am typing). [jpsm on Pine Forum](https://forum.pine64.org/showthread.php?tid=8407&pid=56594#pid56594) seems to have also received a Pinebook Pro with the firmware update already installed.

**Can you write a command to check whether or not the firmware requires updating?**

**Comment by haydenjames** [comment]
+1

**Comment by yawnoc** [comment]
> (although it can't move the pointer while I am typing)

This was because "Disable touchpad while typing" was checked in Mouse Preferences.
Unchecking that, I am able to type and move the pointer via trackpad at the same time.
