### ISSUE TITLE
Frequent random trackpad hangups after applying an update

### ISSUE THREAD

**Issue by barabadzhi** [ayufan-rock64/pinebook-pro-keyboard-updater#2]
After applying an update using this tool I started experiencing frequent random trackpad hangups making it nearly unusable. I believe there is some dependency between scrolling and hangups. When hanged scrolling works fine, but the pointer does not move at all. It is moving only of holding one of the hardware buttons on the trackpad. Solved with restart until appears again in matter of minutes. Any proposals?

**Comment by ayufan** [comment]
Sorry. We do not yet have a good firmware to use. You can rollback to one of the previous ones by modifying which `.hex` file is used.

Once we have it, we will update it.
