### ISSUE TITLE
Running the update breaks the trackpad on the Pinebook Pro

### ISSUE THREAD

**Issue by Feakster** [ayufan-rock64/pinebook-pro-keyboard-updater#3]
After running the script as root the following error message is generated:
```
update pass
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0xfffbe9dc), parent's thread is QThread(0xab2ca308),
current thread is QThread(0xec1201a8)
```
After rebooting, you get one movement and one click out of the trackpad. Then it stops working.

**Comment by dragetd** [comment]
I found a reference to such issue in the Wiki: https://wiki.pine64.org/index.php/Pinebook_Pro_Main_Page#Trackpad

I guess the current FW is broken…? Could you try `lsusb` and/or pasting the dmesg output of the trackpad being detected (somewhere around boot), if it is still detected? Is there anything unusual in the output? Or not detected at all anymore?

**Comment by Feakster** [comment]
Hi,

I have the following output from `lsusb`:

```
benjamin@Scatha:~$ lsusb
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 004: ID 0c45:6321 Microdia 
Bus 001 Device 003: ID 046d:c063 Logitech, Inc. DELL Laser Mouse
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 258a:001e  
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
I'm not sure whether there is anything unusual about the output as this is the first time I've run this command );

The following device is my USB mouse:
```
Bus 001 Device 003: ID 046d:c063 Logitech, Inc. DELL Laser Mouse
```

Ben

**Comment by ayufan** [comment]
Sorry. We do not yet have a good firmware to use. You can rollback to one of the previous ones by modifying which `.hex` file is used.

Once we have it, we will update it.
